#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="erp")]
	public partial class FrameworkDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    partial void InsertFramework_Company(Framework_Company instance);
    partial void UpdateFramework_Company(Framework_Company instance);
    partial void DeleteFramework_Company(Framework_Company instance);
    partial void InsertFramework_Currencies(Framework_Currencies instance);
    partial void UpdateFramework_Currencies(Framework_Currencies instance);
    partial void DeleteFramework_Currencies(Framework_Currencies instance);
    partial void InsertFramework_CurrenciesML(Framework_CurrenciesML instance);
    partial void UpdateFramework_CurrenciesML(Framework_CurrenciesML instance);
    partial void DeleteFramework_CurrenciesML(Framework_CurrenciesML instance);
    partial void InsertFramework_Departements(Framework_Departements instance);
    partial void UpdateFramework_Departements(Framework_Departements instance);
    partial void DeleteFramework_Departements(Framework_Departements instance);
    partial void InsertFramework_DepartementsML(Framework_DepartementsML instance);
    partial void UpdateFramework_DepartementsML(Framework_DepartementsML instance);
    partial void DeleteFramework_DepartementsML(Framework_DepartementsML instance);
    partial void InsertFramework_FormesJuridiques(Framework_FormesJuridiques instance);
    partial void UpdateFramework_FormesJuridiques(Framework_FormesJuridiques instance);
    partial void DeleteFramework_FormesJuridiques(Framework_FormesJuridiques instance);
    partial void InsertFramework_FormesJuridiquesML(Framework_FormesJuridiquesML instance);
    partial void UpdateFramework_FormesJuridiquesML(Framework_FormesJuridiquesML instance);
    partial void DeleteFramework_FormesJuridiquesML(Framework_FormesJuridiquesML instance);
    partial void InsertFramework_Log(Framework_Log instance);
    partial void UpdateFramework_Log(Framework_Log instance);
    partial void DeleteFramework_Log(Framework_Log instance);
    partial void InsertFramework_Pays(Framework_Pays instance);
    partial void UpdateFramework_Pays(Framework_Pays instance);
    partial void DeleteFramework_Pays(Framework_Pays instance);
    partial void InsertFramework_PaysML(Framework_PaysML instance);
    partial void UpdateFramework_PaysML(Framework_PaysML instance);
    partial void DeleteFramework_PaysML(Framework_PaysML instance);
    #endregion
		
		public FrameworkDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FrameworkDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FrameworkDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FrameworkDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Framework_SuggestMatSpec> Framework_SuggestMatSpec
		{
			get
			{
				return this.GetTable<Framework_SuggestMatSpec>();
			}
		}
		
		public System.Data.Linq.Table<Framework_SuggestMaterials> Framework_SuggestMaterials
		{
			get
			{
				return this.GetTable<Framework_SuggestMaterials>();
			}
		}
		
		public System.Data.Linq.Table<Framework_SuggestAll> Framework_SuggestAll
		{
			get
			{
				return this.GetTable<Framework_SuggestAll>();
			}
		}
		
		public System.Data.Linq.Table<Framework_Company> Framework_Company
		{
			get
			{
				return this.GetTable<Framework_Company>();
			}
		}
		
		public System.Data.Linq.Table<Framework_Currencies> Framework_Currencies
		{
			get
			{
				return this.GetTable<Framework_Currencies>();
			}
		}
		
		public System.Data.Linq.Table<Framework_CurrenciesML> Framework_CurrenciesML
		{
			get
			{
				return this.GetTable<Framework_CurrenciesML>();
			}
		}
		
		public System.Data.Linq.Table<Framework_Departements> Framework_Departements
		{
			get
			{
				return this.GetTable<Framework_Departements>();
			}
		}
		
		public System.Data.Linq.Table<Framework_DepartementsML> Framework_DepartementsML
		{
			get
			{
				return this.GetTable<Framework_DepartementsML>();
			}
		}
		
		public System.Data.Linq.Table<Framework_FormesJuridiques> Framework_FormesJuridiques
		{
			get
			{
				return this.GetTable<Framework_FormesJuridiques>();
			}
		}
		
		public System.Data.Linq.Table<Framework_FormesJuridiquesML> Framework_FormesJuridiquesML
		{
			get
			{
				return this.GetTable<Framework_FormesJuridiquesML>();
			}
		}
		
		public System.Data.Linq.Table<Framework_Log> Framework_Log
		{
			get
			{
				return this.GetTable<Framework_Log>();
			}
		}
		
		public System.Data.Linq.Table<Framework_Pays> Framework_Pays
		{
			get
			{
				return this.GetTable<Framework_Pays>();
			}
		}
		
		public System.Data.Linq.Table<Framework_PaysML> Framework_PaysML
		{
			get
			{
				return this.GetTable<Framework_PaysML>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Framework_SuggestMatSpec")]
	public partial class Framework_SuggestMatSpec
	{
		
		private string _ContactID;
		
		private string _ContactName;
		
		public Framework_SuggestMatSpec()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactID", DbType="NVarChar(35)")]
		public string ContactID
		{
			get
			{
				return this._ContactID;
			}
			set
			{
				if ((this._ContactID != value))
				{
					this._ContactID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactName", DbType="VarChar(100)")]
		public string ContactName
		{
			get
			{
				return this._ContactName;
			}
			set
			{
				if ((this._ContactName != value))
				{
					this._ContactName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Framework_SuggestMaterials")]
	public partial class Framework_SuggestMaterials
	{
		
		private string _SearchID;
		
		private string _SearchText;
		
		public Framework_SuggestMaterials()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SearchID", DbType="NVarChar(MAX)")]
		public string SearchID
		{
			get
			{
				return this._SearchID;
			}
			set
			{
				if ((this._SearchID != value))
				{
					this._SearchID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SearchText", DbType="NVarChar(MAX)")]
		public string SearchText
		{
			get
			{
				return this._SearchText;
			}
			set
			{
				if ((this._SearchText != value))
				{
					this._SearchText = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Framework_SuggestAll")]
	public partial class Framework_SuggestAll
	{
		
		private string _ContactID;
		
		private string _ContactName;
		
		public Framework_SuggestAll()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactID", DbType="NVarChar(35)")]
		public string ContactID
		{
			get
			{
				return this._ContactID;
			}
			set
			{
				if ((this._ContactID != value))
				{
					this._ContactID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactName", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string ContactName
		{
			get
			{
				return this._ContactName;
			}
			set
			{
				if ((this._ContactName != value))
				{
					this._ContactName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Framework_Company")]
	public partial class Framework_Company : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _RaisonSociale;
		
		private string _Abbr;
		
		private System.Nullable<int> _ID_Mere;
		
		private System.Nullable<bool> _Etat;
		
		private string _Adresse;
		
		private string _CodePostal;
		
		private string _Ville;
		
		private System.Nullable<int> _ID_Pays;
		
		private System.Nullable<int> _ID_Departement;
		
		private string _Email;
		
		private string _SiteWeb;
		
		private string _Telephone;
		
		private string _Fax;
		
		private string _RC;
		
		private string _MatriculeFiscal;
		
		private string _CodeDouane;
		
		private string _BAN;
		
		private string _NumTVA;
		
		private System.Nullable<bool> _Assujetti;
		
		private System.Nullable<int> _ID_FormeJuridique;
		
		private string _Capital;
		
		private string _logo;
		
		private string _ID_DevisePrincipale;
		
		private System.Nullable<int> _CreatedByUserID;
		
		private System.Nullable<System.DateTime> _CreatedOnDate;
		
		private System.Nullable<int> _LastModifiedByUserID;
		
		private System.Nullable<System.DateTime> _LastModifiedOnDate;
		
		private EntitySet<Framework_Company> _Framework_Company2;
		
		private EntityRef<Framework_Company> _Framework_Company1;
		
		private EntityRef<Framework_Currencies> _Framework_Currencies;
		
		private EntityRef<Framework_Departements> _Framework_Departements;
		
		private EntityRef<Framework_FormesJuridiques> _Framework_FormesJuridiques;
		
		private EntityRef<Framework_Pays> _Framework_Pays;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnRaisonSocialeChanging(string value);
    partial void OnRaisonSocialeChanged();
    partial void OnAbbrChanging(string value);
    partial void OnAbbrChanged();
    partial void OnID_MereChanging(System.Nullable<int> value);
    partial void OnID_MereChanged();
    partial void OnEtatChanging(System.Nullable<bool> value);
    partial void OnEtatChanged();
    partial void OnAdresseChanging(string value);
    partial void OnAdresseChanged();
    partial void OnCodePostalChanging(string value);
    partial void OnCodePostalChanged();
    partial void OnVilleChanging(string value);
    partial void OnVilleChanged();
    partial void OnID_PaysChanging(System.Nullable<int> value);
    partial void OnID_PaysChanged();
    partial void OnID_DepartementChanging(System.Nullable<int> value);
    partial void OnID_DepartementChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSiteWebChanging(string value);
    partial void OnSiteWebChanged();
    partial void OnTelephoneChanging(string value);
    partial void OnTelephoneChanged();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    partial void OnRCChanging(string value);
    partial void OnRCChanged();
    partial void OnMatriculeFiscalChanging(string value);
    partial void OnMatriculeFiscalChanged();
    partial void OnCodeDouaneChanging(string value);
    partial void OnCodeDouaneChanged();
    partial void OnBANChanging(string value);
    partial void OnBANChanged();
    partial void OnNumTVAChanging(string value);
    partial void OnNumTVAChanged();
    partial void OnAssujettiChanging(System.Nullable<bool> value);
    partial void OnAssujettiChanged();
    partial void OnID_FormeJuridiqueChanging(System.Nullable<int> value);
    partial void OnID_FormeJuridiqueChanged();
    partial void OnCapitalChanging(string value);
    partial void OnCapitalChanged();
    partial void OnlogoChanging(string value);
    partial void OnlogoChanged();
    partial void OnID_DevisePrincipaleChanging(string value);
    partial void OnID_DevisePrincipaleChanged();
    partial void OnCreatedByUserIDChanging(System.Nullable<int> value);
    partial void OnCreatedByUserIDChanged();
    partial void OnCreatedOnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnDateChanged();
    partial void OnLastModifiedByUserIDChanging(System.Nullable<int> value);
    partial void OnLastModifiedByUserIDChanged();
    partial void OnLastModifiedOnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastModifiedOnDateChanged();
    #endregion
		
		public Framework_Company()
		{
			this._Framework_Company2 = new EntitySet<Framework_Company>(new Action<Framework_Company>(this.attach_Framework_Company2), new Action<Framework_Company>(this.detach_Framework_Company2));
			this._Framework_Company1 = default(EntityRef<Framework_Company>);
			this._Framework_Currencies = default(EntityRef<Framework_Currencies>);
			this._Framework_Departements = default(EntityRef<Framework_Departements>);
			this._Framework_FormesJuridiques = default(EntityRef<Framework_FormesJuridiques>);
			this._Framework_Pays = default(EntityRef<Framework_Pays>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RaisonSociale", DbType="NVarChar(MAX)")]
		public string RaisonSociale
		{
			get
			{
				return this._RaisonSociale;
			}
			set
			{
				if ((this._RaisonSociale != value))
				{
					this.OnRaisonSocialeChanging(value);
					this.SendPropertyChanging();
					this._RaisonSociale = value;
					this.SendPropertyChanged("RaisonSociale");
					this.OnRaisonSocialeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Abbr", DbType="NVarChar(50)")]
		public string Abbr
		{
			get
			{
				return this._Abbr;
			}
			set
			{
				if ((this._Abbr != value))
				{
					this.OnAbbrChanging(value);
					this.SendPropertyChanging();
					this._Abbr = value;
					this.SendPropertyChanged("Abbr");
					this.OnAbbrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Mere", DbType="Int")]
		public System.Nullable<int> ID_Mere
		{
			get
			{
				return this._ID_Mere;
			}
			set
			{
				if ((this._ID_Mere != value))
				{
					if (this._Framework_Company1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_MereChanging(value);
					this.SendPropertyChanging();
					this._ID_Mere = value;
					this.SendPropertyChanged("ID_Mere");
					this.OnID_MereChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etat", DbType="Bit")]
		public System.Nullable<bool> Etat
		{
			get
			{
				return this._Etat;
			}
			set
			{
				if ((this._Etat != value))
				{
					this.OnEtatChanging(value);
					this.SendPropertyChanging();
					this._Etat = value;
					this.SendPropertyChanged("Etat");
					this.OnEtatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adresse", DbType="NVarChar(MAX)")]
		public string Adresse
		{
			get
			{
				return this._Adresse;
			}
			set
			{
				if ((this._Adresse != value))
				{
					this.OnAdresseChanging(value);
					this.SendPropertyChanging();
					this._Adresse = value;
					this.SendPropertyChanged("Adresse");
					this.OnAdresseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodePostal", DbType="NVarChar(50)")]
		public string CodePostal
		{
			get
			{
				return this._CodePostal;
			}
			set
			{
				if ((this._CodePostal != value))
				{
					this.OnCodePostalChanging(value);
					this.SendPropertyChanging();
					this._CodePostal = value;
					this.SendPropertyChanged("CodePostal");
					this.OnCodePostalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ville", DbType="NVarChar(MAX)")]
		public string Ville
		{
			get
			{
				return this._Ville;
			}
			set
			{
				if ((this._Ville != value))
				{
					this.OnVilleChanging(value);
					this.SendPropertyChanging();
					this._Ville = value;
					this.SendPropertyChanged("Ville");
					this.OnVilleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Pays", DbType="Int")]
		public System.Nullable<int> ID_Pays
		{
			get
			{
				return this._ID_Pays;
			}
			set
			{
				if ((this._ID_Pays != value))
				{
					if (this._Framework_Pays.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_PaysChanging(value);
					this.SendPropertyChanging();
					this._ID_Pays = value;
					this.SendPropertyChanged("ID_Pays");
					this.OnID_PaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Departement", DbType="Int")]
		public System.Nullable<int> ID_Departement
		{
			get
			{
				return this._ID_Departement;
			}
			set
			{
				if ((this._ID_Departement != value))
				{
					if (this._Framework_Departements.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_DepartementChanging(value);
					this.SendPropertyChanging();
					this._ID_Departement = value;
					this.SendPropertyChanged("ID_Departement");
					this.OnID_DepartementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteWeb", DbType="NVarChar(50)")]
		public string SiteWeb
		{
			get
			{
				return this._SiteWeb;
			}
			set
			{
				if ((this._SiteWeb != value))
				{
					this.OnSiteWebChanging(value);
					this.SendPropertyChanging();
					this._SiteWeb = value;
					this.SendPropertyChanged("SiteWeb");
					this.OnSiteWebChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="NVarChar(50)")]
		public string Telephone
		{
			get
			{
				return this._Telephone;
			}
			set
			{
				if ((this._Telephone != value))
				{
					this.OnTelephoneChanging(value);
					this.SendPropertyChanging();
					this._Telephone = value;
					this.SendPropertyChanged("Telephone");
					this.OnTelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="NVarChar(50)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this.OnFaxChanging(value);
					this.SendPropertyChanging();
					this._Fax = value;
					this.SendPropertyChanged("Fax");
					this.OnFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RC", DbType="NVarChar(50)")]
		public string RC
		{
			get
			{
				return this._RC;
			}
			set
			{
				if ((this._RC != value))
				{
					this.OnRCChanging(value);
					this.SendPropertyChanging();
					this._RC = value;
					this.SendPropertyChanged("RC");
					this.OnRCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatriculeFiscal", DbType="NVarChar(50)")]
		public string MatriculeFiscal
		{
			get
			{
				return this._MatriculeFiscal;
			}
			set
			{
				if ((this._MatriculeFiscal != value))
				{
					this.OnMatriculeFiscalChanging(value);
					this.SendPropertyChanging();
					this._MatriculeFiscal = value;
					this.SendPropertyChanged("MatriculeFiscal");
					this.OnMatriculeFiscalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeDouane", DbType="NVarChar(50)")]
		public string CodeDouane
		{
			get
			{
				return this._CodeDouane;
			}
			set
			{
				if ((this._CodeDouane != value))
				{
					this.OnCodeDouaneChanging(value);
					this.SendPropertyChanging();
					this._CodeDouane = value;
					this.SendPropertyChanged("CodeDouane");
					this.OnCodeDouaneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAN", DbType="NVarChar(50)")]
		public string BAN
		{
			get
			{
				return this._BAN;
			}
			set
			{
				if ((this._BAN != value))
				{
					this.OnBANChanging(value);
					this.SendPropertyChanging();
					this._BAN = value;
					this.SendPropertyChanged("BAN");
					this.OnBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumTVA", DbType="NVarChar(50)")]
		public string NumTVA
		{
			get
			{
				return this._NumTVA;
			}
			set
			{
				if ((this._NumTVA != value))
				{
					this.OnNumTVAChanging(value);
					this.SendPropertyChanging();
					this._NumTVA = value;
					this.SendPropertyChanged("NumTVA");
					this.OnNumTVAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Assujetti", DbType="Bit")]
		public System.Nullable<bool> Assujetti
		{
			get
			{
				return this._Assujetti;
			}
			set
			{
				if ((this._Assujetti != value))
				{
					this.OnAssujettiChanging(value);
					this.SendPropertyChanging();
					this._Assujetti = value;
					this.SendPropertyChanged("Assujetti");
					this.OnAssujettiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_FormeJuridique", DbType="Int")]
		public System.Nullable<int> ID_FormeJuridique
		{
			get
			{
				return this._ID_FormeJuridique;
			}
			set
			{
				if ((this._ID_FormeJuridique != value))
				{
					if (this._Framework_FormesJuridiques.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_FormeJuridiqueChanging(value);
					this.SendPropertyChanging();
					this._ID_FormeJuridique = value;
					this.SendPropertyChanged("ID_FormeJuridique");
					this.OnID_FormeJuridiqueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capital", DbType="NChar(10)")]
		public string Capital
		{
			get
			{
				return this._Capital;
			}
			set
			{
				if ((this._Capital != value))
				{
					this.OnCapitalChanging(value);
					this.SendPropertyChanging();
					this._Capital = value;
					this.SendPropertyChanged("Capital");
					this.OnCapitalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logo", DbType="NVarChar(MAX)")]
		public string logo
		{
			get
			{
				return this._logo;
			}
			set
			{
				if ((this._logo != value))
				{
					this.OnlogoChanging(value);
					this.SendPropertyChanging();
					this._logo = value;
					this.SendPropertyChanged("logo");
					this.OnlogoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DevisePrincipale", DbType="NChar(10)")]
		public string ID_DevisePrincipale
		{
			get
			{
				return this._ID_DevisePrincipale;
			}
			set
			{
				if ((this._ID_DevisePrincipale != value))
				{
					if (this._Framework_Currencies.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_DevisePrincipaleChanging(value);
					this.SendPropertyChanging();
					this._ID_DevisePrincipale = value;
					this.SendPropertyChanged("ID_DevisePrincipale");
					this.OnID_DevisePrincipaleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedByUserID", DbType="Int")]
		public System.Nullable<int> CreatedByUserID
		{
			get
			{
				return this._CreatedByUserID;
			}
			set
			{
				if ((this._CreatedByUserID != value))
				{
					this.OnCreatedByUserIDChanging(value);
					this.SendPropertyChanging();
					this._CreatedByUserID = value;
					this.SendPropertyChanged("CreatedByUserID");
					this.OnCreatedByUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOnDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOnDate
		{
			get
			{
				return this._CreatedOnDate;
			}
			set
			{
				if ((this._CreatedOnDate != value))
				{
					this.OnCreatedOnDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedOnDate = value;
					this.SendPropertyChanged("CreatedOnDate");
					this.OnCreatedOnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedByUserID", DbType="Int")]
		public System.Nullable<int> LastModifiedByUserID
		{
			get
			{
				return this._LastModifiedByUserID;
			}
			set
			{
				if ((this._LastModifiedByUserID != value))
				{
					this.OnLastModifiedByUserIDChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedByUserID = value;
					this.SendPropertyChanged("LastModifiedByUserID");
					this.OnLastModifiedByUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedOnDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastModifiedOnDate
		{
			get
			{
				return this._LastModifiedOnDate;
			}
			set
			{
				if ((this._LastModifiedOnDate != value))
				{
					this.OnLastModifiedOnDateChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedOnDate = value;
					this.SendPropertyChanged("LastModifiedOnDate");
					this.OnLastModifiedOnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Framework_Company_Framework_Company", Storage="_Framework_Company2", ThisKey="ID", OtherKey="ID_Mere")]
		public EntitySet<Framework_Company> Framework_Company2
		{
			get
			{
				return this._Framework_Company2;
			}
			set
			{
				this._Framework_Company2.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Framework_Company_Framework_Company", Storage="_Framework_Company1", ThisKey="ID_Mere", OtherKey="ID", IsForeignKey=true)]
		public Framework_Company Framework_Company1
		{
			get
			{
				return this._Framework_Company1.Entity;
			}
			set
			{
				Framework_Company previousValue = this._Framework_Company1.Entity;
				if (((previousValue != value) 
							|| (this._Framework_Company1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Framework_Company1.Entity = null;
						previousValue.Framework_Company2.Remove(this);
					}
					this._Framework_Company1.Entity = value;
					if ((value != null))
					{
						value.Framework_Company2.Add(this);
						this._ID_Mere = value.ID;
					}
					else
					{
						this._ID_Mere = default(Nullable<int>);
					}
					this.SendPropertyChanged("Framework_Company1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Framework_Currencies_Framework_Company", Storage="_Framework_Currencies", ThisKey="ID_DevisePrincipale", OtherKey="code_iso", IsForeignKey=true)]
		public Framework_Currencies Framework_Currencies
		{
			get
			{
				return this._Framework_Currencies.Entity;
			}
			set
			{
				Framework_Currencies previousValue = this._Framework_Currencies.Entity;
				if (((previousValue != value) 
							|| (this._Framework_Currencies.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Framework_Currencies.Entity = null;
						previousValue.Framework_Company.Remove(this);
					}
					this._Framework_Currencies.Entity = value;
					if ((value != null))
					{
						value.Framework_Company.Add(this);
						this._ID_DevisePrincipale = value.code_iso;
					}
					else
					{
						this._ID_DevisePrincipale = default(string);
					}
					this.SendPropertyChanged("Framework_Currencies");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Framework_Departements_Framework_Company", Storage="_Framework_Departements", ThisKey="ID_Departement", OtherKey="ID", IsForeignKey=true)]
		public Framework_Departements Framework_Departements
		{
			get
			{
				return this._Framework_Departements.Entity;
			}
			set
			{
				Framework_Departements previousValue = this._Framework_Departements.Entity;
				if (((previousValue != value) 
							|| (this._Framework_Departements.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Framework_Departements.Entity = null;
						previousValue.Framework_Company.Remove(this);
					}
					this._Framework_Departements.Entity = value;
					if ((value != null))
					{
						value.Framework_Company.Add(this);
						this._ID_Departement = value.ID;
					}
					else
					{
						this._ID_Departement = default(Nullable<int>);
					}
					this.SendPropertyChanged("Framework_Departements");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Framework_FormesJuridiques_Framework_Company", Storage="_Framework_FormesJuridiques", ThisKey="ID_FormeJuridique", OtherKey="ID", IsForeignKey=true)]
		public Framework_FormesJuridiques Framework_FormesJuridiques
		{
			get
			{
				return this._Framework_FormesJuridiques.Entity;
			}
			set
			{
				Framework_FormesJuridiques previousValue = this._Framework_FormesJuridiques.Entity;
				if (((previousValue != value) 
							|| (this._Framework_FormesJuridiques.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Framework_FormesJuridiques.Entity = null;
						previousValue.Framework_Company.Remove(this);
					}
					this._Framework_FormesJuridiques.Entity = value;
					if ((value != null))
					{
						value.Framework_Company.Add(this);
						this._ID_FormeJuridique = value.ID;
					}
					else
					{
						this._ID_FormeJuridique = default(Nullable<int>);
					}
					this.SendPropertyChanged("Framework_FormesJuridiques");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Framework_Pays_Framework_Company", Storage="_Framework_Pays", ThisKey="ID_Pays", OtherKey="ID", IsForeignKey=true)]
		public Framework_Pays Framework_Pays
		{
			get
			{
				return this._Framework_Pays.Entity;
			}
			set
			{
				Framework_Pays previousValue = this._Framework_Pays.Entity;
				if (((previousValue != value) 
							|| (this._Framework_Pays.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Framework_Pays.Entity = null;
						previousValue.Framework_Company.Remove(this);
					}
					this._Framework_Pays.Entity = value;
					if ((value != null))
					{
						value.Framework_Company.Add(this);
						this._ID_Pays = value.ID;
					}
					else
					{
						this._ID_Pays = default(Nullable<int>);
					}
					this.SendPropertyChanged("Framework_Pays");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Framework_Company2(Framework_Company entity)
		{
			this.SendPropertyChanging();
			entity.Framework_Company1 = this;
		}
		
		private void detach_Framework_Company2(Framework_Company entity)
		{
			this.SendPropertyChanging();
			entity.Framework_Company1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Framework_Currencies")]
	public partial class Framework_Currencies : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _code_iso;
		
		private string _label;
		
		private string _unicode;
		
		private System.Nullable<bool> _IsActive;
		
		private EntitySet<Framework_Company> _Framework_Company;
		
		private EntitySet<Framework_CurrenciesML> _Framework_CurrenciesML;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncode_isoChanging(string value);
    partial void Oncode_isoChanged();
    partial void OnlabelChanging(string value);
    partial void OnlabelChanged();
    partial void OnunicodeChanging(string value);
    partial void OnunicodeChanged();
    partial void OnIsActiveChanging(System.Nullable<bool> value);
    partial void OnIsActiveChanged();
    #endregion
		
		public Framework_Currencies()
		{
			this._Framework_Company = new EntitySet<Framework_Company>(new Action<Framework_Company>(this.attach_Framework_Company), new Action<Framework_Company>(this.detach_Framework_Company));
			this._Framework_CurrenciesML = new EntitySet<Framework_CurrenciesML>(new Action<Framework_CurrenciesML>(this.attach_Framework_CurrenciesML), new Action<Framework_CurrenciesML>(this.detach_Framework_CurrenciesML));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code_iso", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string code_iso
		{
			get
			{
				return this._code_iso;
			}
			set
			{
				if ((this._code_iso != value))
				{
					this.Oncode_isoChanging(value);
					this.SendPropertyChanging();
					this._code_iso = value;
					this.SendPropertyChanged("code_iso");
					this.Oncode_isoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_label", DbType="NVarChar(50)")]
		public string label
		{
			get
			{
				return this._label;
			}
			set
			{
				if ((this._label != value))
				{
					this.OnlabelChanging(value);
					this.SendPropertyChanging();
					this._label = value;
					this.SendPropertyChanged("label");
					this.OnlabelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unicode", DbType="NVarChar(50)")]
		public string unicode
		{
			get
			{
				return this._unicode;
			}
			set
			{
				if ((this._unicode != value))
				{
					this.OnunicodeChanging(value);
					this.SendPropertyChanging();
					this._unicode = value;
					this.SendPropertyChanged("unicode");
					this.OnunicodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Framework_Currencies_Framework_Company", Storage="_Framework_Company", ThisKey="code_iso", OtherKey="ID_DevisePrincipale")]
		public EntitySet<Framework_Company> Framework_Company
		{
			get
			{
				return this._Framework_Company;
			}
			set
			{
				this._Framework_Company.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Framework_Currencies_Framework_CurrenciesML", Storage="_Framework_CurrenciesML", ThisKey="code_iso", OtherKey="code_iso")]
		public EntitySet<Framework_CurrenciesML> Framework_CurrenciesML
		{
			get
			{
				return this._Framework_CurrenciesML;
			}
			set
			{
				this._Framework_CurrenciesML.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Framework_Company(Framework_Company entity)
		{
			this.SendPropertyChanging();
			entity.Framework_Currencies = this;
		}
		
		private void detach_Framework_Company(Framework_Company entity)
		{
			this.SendPropertyChanging();
			entity.Framework_Currencies = null;
		}
		
		private void attach_Framework_CurrenciesML(Framework_CurrenciesML entity)
		{
			this.SendPropertyChanging();
			entity.Framework_Currencies = this;
		}
		
		private void detach_Framework_CurrenciesML(Framework_CurrenciesML entity)
		{
			this.SendPropertyChanging();
			entity.Framework_Currencies = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Framework_CurrenciesML")]
	public partial class Framework_CurrenciesML : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _code_iso;
		
		private string _locale;
		
		private string _label;
		
		private EntityRef<Framework_Currencies> _Framework_Currencies;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncode_isoChanging(string value);
    partial void Oncode_isoChanged();
    partial void OnlocaleChanging(string value);
    partial void OnlocaleChanged();
    partial void OnlabelChanging(string value);
    partial void OnlabelChanged();
    #endregion
		
		public Framework_CurrenciesML()
		{
			this._Framework_Currencies = default(EntityRef<Framework_Currencies>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code_iso", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string code_iso
		{
			get
			{
				return this._code_iso;
			}
			set
			{
				if ((this._code_iso != value))
				{
					if (this._Framework_Currencies.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncode_isoChanging(value);
					this.SendPropertyChanging();
					this._code_iso = value;
					this.SendPropertyChanged("code_iso");
					this.Oncode_isoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_locale", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string locale
		{
			get
			{
				return this._locale;
			}
			set
			{
				if ((this._locale != value))
				{
					this.OnlocaleChanging(value);
					this.SendPropertyChanging();
					this._locale = value;
					this.SendPropertyChanged("locale");
					this.OnlocaleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_label", DbType="NChar(10)")]
		public string label
		{
			get
			{
				return this._label;
			}
			set
			{
				if ((this._label != value))
				{
					this.OnlabelChanging(value);
					this.SendPropertyChanging();
					this._label = value;
					this.SendPropertyChanged("label");
					this.OnlabelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Framework_Currencies_Framework_CurrenciesML", Storage="_Framework_Currencies", ThisKey="code_iso", OtherKey="code_iso", IsForeignKey=true)]
		public Framework_Currencies Framework_Currencies
		{
			get
			{
				return this._Framework_Currencies.Entity;
			}
			set
			{
				Framework_Currencies previousValue = this._Framework_Currencies.Entity;
				if (((previousValue != value) 
							|| (this._Framework_Currencies.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Framework_Currencies.Entity = null;
						previousValue.Framework_CurrenciesML.Remove(this);
					}
					this._Framework_Currencies.Entity = value;
					if ((value != null))
					{
						value.Framework_CurrenciesML.Add(this);
						this._code_iso = value.code_iso;
					}
					else
					{
						this._code_iso = default(string);
					}
					this.SendPropertyChanged("Framework_Currencies");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Framework_Departements")]
	public partial class Framework_Departements : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Designation;
		
		private System.Nullable<int> _ID_Pays;
		
		private System.Nullable<int> _CreatedByUserID;
		
		private System.Nullable<System.DateTime> _CreatedOnDate;
		
		private System.Nullable<int> _LastModifiedByUserID;
		
		private System.Nullable<System.DateTime> _LastModifiedOnDate;
		
		private EntitySet<Framework_Company> _Framework_Company;
		
		private EntitySet<Framework_DepartementsML> _Framework_DepartementsML;
		
		private EntityRef<Framework_Pays> _Framework_Pays;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDesignationChanging(string value);
    partial void OnDesignationChanged();
    partial void OnID_PaysChanging(System.Nullable<int> value);
    partial void OnID_PaysChanged();
    partial void OnCreatedByUserIDChanging(System.Nullable<int> value);
    partial void OnCreatedByUserIDChanged();
    partial void OnCreatedOnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnDateChanged();
    partial void OnLastModifiedByUserIDChanging(System.Nullable<int> value);
    partial void OnLastModifiedByUserIDChanged();
    partial void OnLastModifiedOnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastModifiedOnDateChanged();
    #endregion
		
		public Framework_Departements()
		{
			this._Framework_Company = new EntitySet<Framework_Company>(new Action<Framework_Company>(this.attach_Framework_Company), new Action<Framework_Company>(this.detach_Framework_Company));
			this._Framework_DepartementsML = new EntitySet<Framework_DepartementsML>(new Action<Framework_DepartementsML>(this.attach_Framework_DepartementsML), new Action<Framework_DepartementsML>(this.detach_Framework_DepartementsML));
			this._Framework_Pays = default(EntityRef<Framework_Pays>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Designation", DbType="NVarChar(MAX)")]
		public string Designation
		{
			get
			{
				return this._Designation;
			}
			set
			{
				if ((this._Designation != value))
				{
					this.OnDesignationChanging(value);
					this.SendPropertyChanging();
					this._Designation = value;
					this.SendPropertyChanged("Designation");
					this.OnDesignationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Pays", DbType="Int")]
		public System.Nullable<int> ID_Pays
		{
			get
			{
				return this._ID_Pays;
			}
			set
			{
				if ((this._ID_Pays != value))
				{
					if (this._Framework_Pays.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_PaysChanging(value);
					this.SendPropertyChanging();
					this._ID_Pays = value;
					this.SendPropertyChanged("ID_Pays");
					this.OnID_PaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedByUserID", DbType="Int")]
		public System.Nullable<int> CreatedByUserID
		{
			get
			{
				return this._CreatedByUserID;
			}
			set
			{
				if ((this._CreatedByUserID != value))
				{
					this.OnCreatedByUserIDChanging(value);
					this.SendPropertyChanging();
					this._CreatedByUserID = value;
					this.SendPropertyChanged("CreatedByUserID");
					this.OnCreatedByUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOnDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOnDate
		{
			get
			{
				return this._CreatedOnDate;
			}
			set
			{
				if ((this._CreatedOnDate != value))
				{
					this.OnCreatedOnDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedOnDate = value;
					this.SendPropertyChanged("CreatedOnDate");
					this.OnCreatedOnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedByUserID", DbType="Int")]
		public System.Nullable<int> LastModifiedByUserID
		{
			get
			{
				return this._LastModifiedByUserID;
			}
			set
			{
				if ((this._LastModifiedByUserID != value))
				{
					this.OnLastModifiedByUserIDChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedByUserID = value;
					this.SendPropertyChanged("LastModifiedByUserID");
					this.OnLastModifiedByUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedOnDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastModifiedOnDate
		{
			get
			{
				return this._LastModifiedOnDate;
			}
			set
			{
				if ((this._LastModifiedOnDate != value))
				{
					this.OnLastModifiedOnDateChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedOnDate = value;
					this.SendPropertyChanged("LastModifiedOnDate");
					this.OnLastModifiedOnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Framework_Departements_Framework_Company", Storage="_Framework_Company", ThisKey="ID", OtherKey="ID_Departement")]
		public EntitySet<Framework_Company> Framework_Company
		{
			get
			{
				return this._Framework_Company;
			}
			set
			{
				this._Framework_Company.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Framework_Departements_Framework_DepartementsML", Storage="_Framework_DepartementsML", ThisKey="ID", OtherKey="ID_Departement")]
		public EntitySet<Framework_DepartementsML> Framework_DepartementsML
		{
			get
			{
				return this._Framework_DepartementsML;
			}
			set
			{
				this._Framework_DepartementsML.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Framework_Pays_Framework_Departements", Storage="_Framework_Pays", ThisKey="ID_Pays", OtherKey="ID", IsForeignKey=true)]
		public Framework_Pays Framework_Pays
		{
			get
			{
				return this._Framework_Pays.Entity;
			}
			set
			{
				Framework_Pays previousValue = this._Framework_Pays.Entity;
				if (((previousValue != value) 
							|| (this._Framework_Pays.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Framework_Pays.Entity = null;
						previousValue.Framework_Departements.Remove(this);
					}
					this._Framework_Pays.Entity = value;
					if ((value != null))
					{
						value.Framework_Departements.Add(this);
						this._ID_Pays = value.ID;
					}
					else
					{
						this._ID_Pays = default(Nullable<int>);
					}
					this.SendPropertyChanged("Framework_Pays");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Framework_Company(Framework_Company entity)
		{
			this.SendPropertyChanging();
			entity.Framework_Departements = this;
		}
		
		private void detach_Framework_Company(Framework_Company entity)
		{
			this.SendPropertyChanging();
			entity.Framework_Departements = null;
		}
		
		private void attach_Framework_DepartementsML(Framework_DepartementsML entity)
		{
			this.SendPropertyChanging();
			entity.Framework_Departements = this;
		}
		
		private void detach_Framework_DepartementsML(Framework_DepartementsML entity)
		{
			this.SendPropertyChanging();
			entity.Framework_Departements = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Framework_DepartementsML")]
	public partial class Framework_DepartementsML : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Departement;
		
		private string _Locale;
		
		private string _Designation;
		
		private EntityRef<Framework_Departements> _Framework_Departements;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_DepartementChanging(int value);
    partial void OnID_DepartementChanged();
    partial void OnLocaleChanging(string value);
    partial void OnLocaleChanged();
    partial void OnDesignationChanging(string value);
    partial void OnDesignationChanged();
    #endregion
		
		public Framework_DepartementsML()
		{
			this._Framework_Departements = default(EntityRef<Framework_Departements>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Departement", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_Departement
		{
			get
			{
				return this._ID_Departement;
			}
			set
			{
				if ((this._ID_Departement != value))
				{
					if (this._Framework_Departements.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_DepartementChanging(value);
					this.SendPropertyChanging();
					this._ID_Departement = value;
					this.SendPropertyChanged("ID_Departement");
					this.OnID_DepartementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Locale", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Locale
		{
			get
			{
				return this._Locale;
			}
			set
			{
				if ((this._Locale != value))
				{
					this.OnLocaleChanging(value);
					this.SendPropertyChanging();
					this._Locale = value;
					this.SendPropertyChanged("Locale");
					this.OnLocaleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Designation", DbType="NVarChar(MAX)")]
		public string Designation
		{
			get
			{
				return this._Designation;
			}
			set
			{
				if ((this._Designation != value))
				{
					this.OnDesignationChanging(value);
					this.SendPropertyChanging();
					this._Designation = value;
					this.SendPropertyChanged("Designation");
					this.OnDesignationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Framework_Departements_Framework_DepartementsML", Storage="_Framework_Departements", ThisKey="ID_Departement", OtherKey="ID", IsForeignKey=true)]
		public Framework_Departements Framework_Departements
		{
			get
			{
				return this._Framework_Departements.Entity;
			}
			set
			{
				Framework_Departements previousValue = this._Framework_Departements.Entity;
				if (((previousValue != value) 
							|| (this._Framework_Departements.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Framework_Departements.Entity = null;
						previousValue.Framework_DepartementsML.Remove(this);
					}
					this._Framework_Departements.Entity = value;
					if ((value != null))
					{
						value.Framework_DepartementsML.Add(this);
						this._ID_Departement = value.ID;
					}
					else
					{
						this._ID_Departement = default(int);
					}
					this.SendPropertyChanged("Framework_Departements");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Framework_FormesJuridiques")]
	public partial class Framework_FormesJuridiques : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Designation;
		
		private System.Nullable<int> _CreatedByUserID;
		
		private System.Nullable<System.DateTime> _CreatedOnDate;
		
		private System.Nullable<int> _LastModifiedByUserID;
		
		private System.Nullable<System.DateTime> _LastModifiedOnDate;
		
		private EntitySet<Framework_Company> _Framework_Company;
		
		private EntitySet<Framework_FormesJuridiquesML> _Framework_FormesJuridiquesML;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDesignationChanging(string value);
    partial void OnDesignationChanged();
    partial void OnCreatedByUserIDChanging(System.Nullable<int> value);
    partial void OnCreatedByUserIDChanged();
    partial void OnCreatedOnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnDateChanged();
    partial void OnLastModifiedByUserIDChanging(System.Nullable<int> value);
    partial void OnLastModifiedByUserIDChanged();
    partial void OnLastModifiedOnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastModifiedOnDateChanged();
    #endregion
		
		public Framework_FormesJuridiques()
		{
			this._Framework_Company = new EntitySet<Framework_Company>(new Action<Framework_Company>(this.attach_Framework_Company), new Action<Framework_Company>(this.detach_Framework_Company));
			this._Framework_FormesJuridiquesML = new EntitySet<Framework_FormesJuridiquesML>(new Action<Framework_FormesJuridiquesML>(this.attach_Framework_FormesJuridiquesML), new Action<Framework_FormesJuridiquesML>(this.detach_Framework_FormesJuridiquesML));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Designation", DbType="NVarChar(MAX)")]
		public string Designation
		{
			get
			{
				return this._Designation;
			}
			set
			{
				if ((this._Designation != value))
				{
					this.OnDesignationChanging(value);
					this.SendPropertyChanging();
					this._Designation = value;
					this.SendPropertyChanged("Designation");
					this.OnDesignationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedByUserID", DbType="Int")]
		public System.Nullable<int> CreatedByUserID
		{
			get
			{
				return this._CreatedByUserID;
			}
			set
			{
				if ((this._CreatedByUserID != value))
				{
					this.OnCreatedByUserIDChanging(value);
					this.SendPropertyChanging();
					this._CreatedByUserID = value;
					this.SendPropertyChanged("CreatedByUserID");
					this.OnCreatedByUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOnDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOnDate
		{
			get
			{
				return this._CreatedOnDate;
			}
			set
			{
				if ((this._CreatedOnDate != value))
				{
					this.OnCreatedOnDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedOnDate = value;
					this.SendPropertyChanged("CreatedOnDate");
					this.OnCreatedOnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedByUserID", DbType="Int")]
		public System.Nullable<int> LastModifiedByUserID
		{
			get
			{
				return this._LastModifiedByUserID;
			}
			set
			{
				if ((this._LastModifiedByUserID != value))
				{
					this.OnLastModifiedByUserIDChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedByUserID = value;
					this.SendPropertyChanged("LastModifiedByUserID");
					this.OnLastModifiedByUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedOnDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastModifiedOnDate
		{
			get
			{
				return this._LastModifiedOnDate;
			}
			set
			{
				if ((this._LastModifiedOnDate != value))
				{
					this.OnLastModifiedOnDateChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedOnDate = value;
					this.SendPropertyChanged("LastModifiedOnDate");
					this.OnLastModifiedOnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Framework_FormesJuridiques_Framework_Company", Storage="_Framework_Company", ThisKey="ID", OtherKey="ID_FormeJuridique")]
		public EntitySet<Framework_Company> Framework_Company
		{
			get
			{
				return this._Framework_Company;
			}
			set
			{
				this._Framework_Company.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Framework_FormesJuridiques_Framework_FormesJuridiquesML", Storage="_Framework_FormesJuridiquesML", ThisKey="ID", OtherKey="ID_FormesJuridiques")]
		public EntitySet<Framework_FormesJuridiquesML> Framework_FormesJuridiquesML
		{
			get
			{
				return this._Framework_FormesJuridiquesML;
			}
			set
			{
				this._Framework_FormesJuridiquesML.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Framework_Company(Framework_Company entity)
		{
			this.SendPropertyChanging();
			entity.Framework_FormesJuridiques = this;
		}
		
		private void detach_Framework_Company(Framework_Company entity)
		{
			this.SendPropertyChanging();
			entity.Framework_FormesJuridiques = null;
		}
		
		private void attach_Framework_FormesJuridiquesML(Framework_FormesJuridiquesML entity)
		{
			this.SendPropertyChanging();
			entity.Framework_FormesJuridiques = this;
		}
		
		private void detach_Framework_FormesJuridiquesML(Framework_FormesJuridiquesML entity)
		{
			this.SendPropertyChanging();
			entity.Framework_FormesJuridiques = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Framework_FormesJuridiquesML")]
	public partial class Framework_FormesJuridiquesML : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_FormesJuridiques;
		
		private string _Locale;
		
		private string _Designation;
		
		private EntityRef<Framework_FormesJuridiques> _Framework_FormesJuridiques;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_FormesJuridiquesChanging(int value);
    partial void OnID_FormesJuridiquesChanged();
    partial void OnLocaleChanging(string value);
    partial void OnLocaleChanged();
    partial void OnDesignationChanging(string value);
    partial void OnDesignationChanged();
    #endregion
		
		public Framework_FormesJuridiquesML()
		{
			this._Framework_FormesJuridiques = default(EntityRef<Framework_FormesJuridiques>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_FormesJuridiques", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_FormesJuridiques
		{
			get
			{
				return this._ID_FormesJuridiques;
			}
			set
			{
				if ((this._ID_FormesJuridiques != value))
				{
					if (this._Framework_FormesJuridiques.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_FormesJuridiquesChanging(value);
					this.SendPropertyChanging();
					this._ID_FormesJuridiques = value;
					this.SendPropertyChanged("ID_FormesJuridiques");
					this.OnID_FormesJuridiquesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Locale", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Locale
		{
			get
			{
				return this._Locale;
			}
			set
			{
				if ((this._Locale != value))
				{
					this.OnLocaleChanging(value);
					this.SendPropertyChanging();
					this._Locale = value;
					this.SendPropertyChanged("Locale");
					this.OnLocaleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Designation", DbType="NVarChar(MAX)")]
		public string Designation
		{
			get
			{
				return this._Designation;
			}
			set
			{
				if ((this._Designation != value))
				{
					this.OnDesignationChanging(value);
					this.SendPropertyChanging();
					this._Designation = value;
					this.SendPropertyChanged("Designation");
					this.OnDesignationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Framework_FormesJuridiques_Framework_FormesJuridiquesML", Storage="_Framework_FormesJuridiques", ThisKey="ID_FormesJuridiques", OtherKey="ID", IsForeignKey=true)]
		public Framework_FormesJuridiques Framework_FormesJuridiques
		{
			get
			{
				return this._Framework_FormesJuridiques.Entity;
			}
			set
			{
				Framework_FormesJuridiques previousValue = this._Framework_FormesJuridiques.Entity;
				if (((previousValue != value) 
							|| (this._Framework_FormesJuridiques.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Framework_FormesJuridiques.Entity = null;
						previousValue.Framework_FormesJuridiquesML.Remove(this);
					}
					this._Framework_FormesJuridiques.Entity = value;
					if ((value != null))
					{
						value.Framework_FormesJuridiquesML.Add(this);
						this._ID_FormesJuridiques = value.ID;
					}
					else
					{
						this._ID_FormesJuridiques = default(int);
					}
					this.SendPropertyChanged("Framework_FormesJuridiques");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Framework_Log")]
	public partial class Framework_Log : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Message;
		
		private System.DateTime _Created;
		
		private int _Id;
		
		private int _UserId;
		
		private string _Type;
		
		private string _Source;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    partial void OnCreatedChanging(System.DateTime value);
    partial void OnCreatedChanged();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnSourceChanging(string value);
    partial void OnSourceChanged();
    #endregion
		
		public Framework_Log()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this.OnMessageChanging(value);
					this.SendPropertyChanging();
					this._Message = value;
					this.SendPropertyChanged("Message");
					this.OnMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="DateTime NOT NULL")]
		public System.DateTime Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL")]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(50)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Source", DbType="NVarChar(300)")]
		public string Source
		{
			get
			{
				return this._Source;
			}
			set
			{
				if ((this._Source != value))
				{
					this.OnSourceChanging(value);
					this.SendPropertyChanging();
					this._Source = value;
					this.SendPropertyChanged("Source");
					this.OnSourceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Framework_Pays")]
	public partial class Framework_Pays : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Libelle;
		
		private string _Code;
		
		private System.Nullable<bool> _IsActive;
		
		private EntitySet<Framework_Company> _Framework_Company;
		
		private EntitySet<Framework_Departements> _Framework_Departements;
		
		private EntitySet<Framework_PaysML> _Framework_PaysML;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnLibelleChanging(string value);
    partial void OnLibelleChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnIsActiveChanging(System.Nullable<bool> value);
    partial void OnIsActiveChanged();
    #endregion
		
		public Framework_Pays()
		{
			this._Framework_Company = new EntitySet<Framework_Company>(new Action<Framework_Company>(this.attach_Framework_Company), new Action<Framework_Company>(this.detach_Framework_Company));
			this._Framework_Departements = new EntitySet<Framework_Departements>(new Action<Framework_Departements>(this.attach_Framework_Departements), new Action<Framework_Departements>(this.detach_Framework_Departements));
			this._Framework_PaysML = new EntitySet<Framework_PaysML>(new Action<Framework_PaysML>(this.attach_Framework_PaysML), new Action<Framework_PaysML>(this.detach_Framework_PaysML));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Libelle", DbType="NVarChar(MAX)")]
		public string Libelle
		{
			get
			{
				return this._Libelle;
			}
			set
			{
				if ((this._Libelle != value))
				{
					this.OnLibelleChanging(value);
					this.SendPropertyChanging();
					this._Libelle = value;
					this.SendPropertyChanged("Libelle");
					this.OnLibelleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="VarChar(50)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Framework_Pays_Framework_Company", Storage="_Framework_Company", ThisKey="ID", OtherKey="ID_Pays")]
		public EntitySet<Framework_Company> Framework_Company
		{
			get
			{
				return this._Framework_Company;
			}
			set
			{
				this._Framework_Company.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Framework_Pays_Framework_Departements", Storage="_Framework_Departements", ThisKey="ID", OtherKey="ID_Pays")]
		public EntitySet<Framework_Departements> Framework_Departements
		{
			get
			{
				return this._Framework_Departements;
			}
			set
			{
				this._Framework_Departements.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Framework_Pays_Framework_PaysML", Storage="_Framework_PaysML", ThisKey="ID", OtherKey="ID_Pays")]
		public EntitySet<Framework_PaysML> Framework_PaysML
		{
			get
			{
				return this._Framework_PaysML;
			}
			set
			{
				this._Framework_PaysML.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Framework_Company(Framework_Company entity)
		{
			this.SendPropertyChanging();
			entity.Framework_Pays = this;
		}
		
		private void detach_Framework_Company(Framework_Company entity)
		{
			this.SendPropertyChanging();
			entity.Framework_Pays = null;
		}
		
		private void attach_Framework_Departements(Framework_Departements entity)
		{
			this.SendPropertyChanging();
			entity.Framework_Pays = this;
		}
		
		private void detach_Framework_Departements(Framework_Departements entity)
		{
			this.SendPropertyChanging();
			entity.Framework_Pays = null;
		}
		
		private void attach_Framework_PaysML(Framework_PaysML entity)
		{
			this.SendPropertyChanging();
			entity.Framework_Pays = this;
		}
		
		private void detach_Framework_PaysML(Framework_PaysML entity)
		{
			this.SendPropertyChanging();
			entity.Framework_Pays = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Framework_PaysML")]
	public partial class Framework_PaysML : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Pays;
		
		private string _Locale;
		
		private string _Libelle;
		
		private EntityRef<Framework_Pays> _Framework_Pays;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PaysChanging(int value);
    partial void OnID_PaysChanged();
    partial void OnLocaleChanging(string value);
    partial void OnLocaleChanged();
    partial void OnLibelleChanging(string value);
    partial void OnLibelleChanged();
    #endregion
		
		public Framework_PaysML()
		{
			this._Framework_Pays = default(EntityRef<Framework_Pays>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Pays", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_Pays
		{
			get
			{
				return this._ID_Pays;
			}
			set
			{
				if ((this._ID_Pays != value))
				{
					if (this._Framework_Pays.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_PaysChanging(value);
					this.SendPropertyChanging();
					this._ID_Pays = value;
					this.SendPropertyChanged("ID_Pays");
					this.OnID_PaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Locale", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Locale
		{
			get
			{
				return this._Locale;
			}
			set
			{
				if ((this._Locale != value))
				{
					this.OnLocaleChanging(value);
					this.SendPropertyChanging();
					this._Locale = value;
					this.SendPropertyChanged("Locale");
					this.OnLocaleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Libelle", DbType="NVarChar(MAX)")]
		public string Libelle
		{
			get
			{
				return this._Libelle;
			}
			set
			{
				if ((this._Libelle != value))
				{
					this.OnLibelleChanging(value);
					this.SendPropertyChanging();
					this._Libelle = value;
					this.SendPropertyChanged("Libelle");
					this.OnLibelleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Framework_Pays_Framework_PaysML", Storage="_Framework_Pays", ThisKey="ID_Pays", OtherKey="ID", IsForeignKey=true)]
		public Framework_Pays Framework_Pays
		{
			get
			{
				return this._Framework_Pays.Entity;
			}
			set
			{
				Framework_Pays previousValue = this._Framework_Pays.Entity;
				if (((previousValue != value) 
							|| (this._Framework_Pays.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Framework_Pays.Entity = null;
						previousValue.Framework_PaysML.Remove(this);
					}
					this._Framework_Pays.Entity = value;
					if ((value != null))
					{
						value.Framework_PaysML.Add(this);
						this._ID_Pays = value.ID;
					}
					else
					{
						this._ID_Pays = default(int);
					}
					this.SendPropertyChanged("Framework_Pays");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
