#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="erp")]
	public partial class GestionTiersDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    partial void InsertTiers_Activites(Tiers_Activites instance);
    partial void UpdateTiers_Activites(Tiers_Activites instance);
    partial void DeleteTiers_Activites(Tiers_Activites instance);
    partial void InsertTiers_Tiers(Tiers_Tiers instance);
    partial void UpdateTiers_Tiers(Tiers_Tiers instance);
    partial void DeleteTiers_Tiers(Tiers_Tiers instance);
    partial void InsertTiers_Types(Tiers_Types instance);
    partial void UpdateTiers_Types(Tiers_Types instance);
    partial void DeleteTiers_Types(Tiers_Types instance);
    #endregion
		
		public GestionTiersDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GestionTiersDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GestionTiersDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GestionTiersDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tiers_Activites> Tiers_Activites
		{
			get
			{
				return this.GetTable<Tiers_Activites>();
			}
		}
		
		public System.Data.Linq.Table<Tiers_Tiers> Tiers_Tiers
		{
			get
			{
				return this.GetTable<Tiers_Tiers>();
			}
		}
		
		public System.Data.Linq.Table<Tiers_Types> Tiers_Types
		{
			get
			{
				return this.GetTable<Tiers_Types>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tiers_Activites")]
	public partial class Tiers_Activites : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Designation;
		
		private System.Nullable<int> _CreatedByUserID;
		
		private System.Nullable<System.DateTime> _CreatedOnDate;
		
		private System.Nullable<int> _LastModifiedByUserID;
		
		private System.Nullable<System.DateTime> _LastModifiedOnDate;
		
		private EntitySet<Tiers_Tiers> _Tiers_Tiers;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDesignationChanging(string value);
    partial void OnDesignationChanged();
    partial void OnCreatedByUserIDChanging(System.Nullable<int> value);
    partial void OnCreatedByUserIDChanged();
    partial void OnCreatedOnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnDateChanged();
    partial void OnLastModifiedByUserIDChanging(System.Nullable<int> value);
    partial void OnLastModifiedByUserIDChanged();
    partial void OnLastModifiedOnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastModifiedOnDateChanged();
    #endregion
		
		public Tiers_Activites()
		{
			this._Tiers_Tiers = new EntitySet<Tiers_Tiers>(new Action<Tiers_Tiers>(this.attach_Tiers_Tiers), new Action<Tiers_Tiers>(this.detach_Tiers_Tiers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Designation", DbType="NVarChar(MAX)")]
		public string Designation
		{
			get
			{
				return this._Designation;
			}
			set
			{
				if ((this._Designation != value))
				{
					this.OnDesignationChanging(value);
					this.SendPropertyChanging();
					this._Designation = value;
					this.SendPropertyChanged("Designation");
					this.OnDesignationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedByUserID", DbType="Int")]
		public System.Nullable<int> CreatedByUserID
		{
			get
			{
				return this._CreatedByUserID;
			}
			set
			{
				if ((this._CreatedByUserID != value))
				{
					this.OnCreatedByUserIDChanging(value);
					this.SendPropertyChanging();
					this._CreatedByUserID = value;
					this.SendPropertyChanged("CreatedByUserID");
					this.OnCreatedByUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOnDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOnDate
		{
			get
			{
				return this._CreatedOnDate;
			}
			set
			{
				if ((this._CreatedOnDate != value))
				{
					this.OnCreatedOnDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedOnDate = value;
					this.SendPropertyChanged("CreatedOnDate");
					this.OnCreatedOnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedByUserID", DbType="Int")]
		public System.Nullable<int> LastModifiedByUserID
		{
			get
			{
				return this._LastModifiedByUserID;
			}
			set
			{
				if ((this._LastModifiedByUserID != value))
				{
					this.OnLastModifiedByUserIDChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedByUserID = value;
					this.SendPropertyChanged("LastModifiedByUserID");
					this.OnLastModifiedByUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedOnDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastModifiedOnDate
		{
			get
			{
				return this._LastModifiedOnDate;
			}
			set
			{
				if ((this._LastModifiedOnDate != value))
				{
					this.OnLastModifiedOnDateChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedOnDate = value;
					this.SendPropertyChanged("LastModifiedOnDate");
					this.OnLastModifiedOnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tiers_Activites_Tiers_Tiers", Storage="_Tiers_Tiers", ThisKey="ID", OtherKey="ID_Activite")]
		public EntitySet<Tiers_Tiers> Tiers_Tiers
		{
			get
			{
				return this._Tiers_Tiers;
			}
			set
			{
				this._Tiers_Tiers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tiers_Tiers(Tiers_Tiers entity)
		{
			this.SendPropertyChanging();
			entity.Tiers_Activites = this;
		}
		
		private void detach_Tiers_Tiers(Tiers_Tiers entity)
		{
			this.SendPropertyChanging();
			entity.Tiers_Activites = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tiers_Tiers")]
	public partial class Tiers_Tiers : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _RaisonSociale;
		
		private string _Abbr;
		
		private System.Nullable<int> _ID_Mere;
		
		private System.Nullable<bool> _Etat;
		
		private System.Nullable<bool> _IsClient;
		
		private System.Nullable<bool> _IsSupplier;
		
		private string _CodeClient;
		
		private string _CodeSupplier;
		
		private string _Codebarre;
		
		private string _Adresse;
		
		private string _CodePostal;
		
		private string _Ville;
		
		private System.Nullable<int> _ID_Pays;
		
		private System.Nullable<int> _ID_Departement;
		
		private string _Email;
		
		private string _SiteWeb;
		
		private string _Telephone;
		
		private string _Fax;
		
		private string _RC;
		
		private string _MatriculeFiscal;
		
		private string _CodeDouane;
		
		private string _BAN;
		
		private string _NumTVA;
		
		private System.Nullable<bool> _Assujetti;
		
		private System.Nullable<int> _ID_Type;
		
		private System.Nullable<int> _ID_FormeJuridique;
		
		private string _Capital;
		
		private string _ID_Devise;
		
		private string _logo;
		
		private System.Nullable<int> _ID_Activite;
		
		private System.Nullable<int> _CreatedByUserID;
		
		private System.Nullable<System.DateTime> _CreatedOnDate;
		
		private System.Nullable<int> _LastModifiedByUserID;
		
		private System.Nullable<System.DateTime> _LastModifiedOnDate;
		
		private EntitySet<Tiers_Tiers> _Tiers_Tiers2;
		
		private EntityRef<Tiers_Activites> _Tiers_Activites;
		
		private EntityRef<Tiers_Tiers> _Tiers_Tiers1;
		
		private EntityRef<Tiers_Types> _Tiers_Types;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnRaisonSocialeChanging(string value);
    partial void OnRaisonSocialeChanged();
    partial void OnAbbrChanging(string value);
    partial void OnAbbrChanged();
    partial void OnID_MereChanging(System.Nullable<int> value);
    partial void OnID_MereChanged();
    partial void OnEtatChanging(System.Nullable<bool> value);
    partial void OnEtatChanged();
    partial void OnIsClientChanging(System.Nullable<bool> value);
    partial void OnIsClientChanged();
    partial void OnIsSupplierChanging(System.Nullable<bool> value);
    partial void OnIsSupplierChanged();
    partial void OnCodeClientChanging(string value);
    partial void OnCodeClientChanged();
    partial void OnCodeSupplierChanging(string value);
    partial void OnCodeSupplierChanged();
    partial void OnCodebarreChanging(string value);
    partial void OnCodebarreChanged();
    partial void OnAdresseChanging(string value);
    partial void OnAdresseChanged();
    partial void OnCodePostalChanging(string value);
    partial void OnCodePostalChanged();
    partial void OnVilleChanging(string value);
    partial void OnVilleChanged();
    partial void OnID_PaysChanging(System.Nullable<int> value);
    partial void OnID_PaysChanged();
    partial void OnID_DepartementChanging(System.Nullable<int> value);
    partial void OnID_DepartementChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSiteWebChanging(string value);
    partial void OnSiteWebChanged();
    partial void OnTelephoneChanging(string value);
    partial void OnTelephoneChanged();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    partial void OnRCChanging(string value);
    partial void OnRCChanged();
    partial void OnMatriculeFiscalChanging(string value);
    partial void OnMatriculeFiscalChanged();
    partial void OnCodeDouaneChanging(string value);
    partial void OnCodeDouaneChanged();
    partial void OnBANChanging(string value);
    partial void OnBANChanged();
    partial void OnNumTVAChanging(string value);
    partial void OnNumTVAChanged();
    partial void OnAssujettiChanging(System.Nullable<bool> value);
    partial void OnAssujettiChanged();
    partial void OnID_TypeChanging(System.Nullable<int> value);
    partial void OnID_TypeChanged();
    partial void OnID_FormeJuridiqueChanging(System.Nullable<int> value);
    partial void OnID_FormeJuridiqueChanged();
    partial void OnCapitalChanging(string value);
    partial void OnCapitalChanged();
    partial void OnID_DeviseChanging(string value);
    partial void OnID_DeviseChanged();
    partial void OnlogoChanging(string value);
    partial void OnlogoChanged();
    partial void OnID_ActiviteChanging(System.Nullable<int> value);
    partial void OnID_ActiviteChanged();
    partial void OnCreatedByUserIDChanging(System.Nullable<int> value);
    partial void OnCreatedByUserIDChanged();
    partial void OnCreatedOnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnDateChanged();
    partial void OnLastModifiedByUserIDChanging(System.Nullable<int> value);
    partial void OnLastModifiedByUserIDChanged();
    partial void OnLastModifiedOnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastModifiedOnDateChanged();
    #endregion
		
		public Tiers_Tiers()
		{
			this._Tiers_Tiers2 = new EntitySet<Tiers_Tiers>(new Action<Tiers_Tiers>(this.attach_Tiers_Tiers2), new Action<Tiers_Tiers>(this.detach_Tiers_Tiers2));
			this._Tiers_Activites = default(EntityRef<Tiers_Activites>);
			this._Tiers_Tiers1 = default(EntityRef<Tiers_Tiers>);
			this._Tiers_Types = default(EntityRef<Tiers_Types>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RaisonSociale", DbType="NVarChar(MAX)")]
		public string RaisonSociale
		{
			get
			{
				return this._RaisonSociale;
			}
			set
			{
				if ((this._RaisonSociale != value))
				{
					this.OnRaisonSocialeChanging(value);
					this.SendPropertyChanging();
					this._RaisonSociale = value;
					this.SendPropertyChanged("RaisonSociale");
					this.OnRaisonSocialeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Abbr", DbType="NVarChar(50)")]
		public string Abbr
		{
			get
			{
				return this._Abbr;
			}
			set
			{
				if ((this._Abbr != value))
				{
					this.OnAbbrChanging(value);
					this.SendPropertyChanging();
					this._Abbr = value;
					this.SendPropertyChanged("Abbr");
					this.OnAbbrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Mere", DbType="Int")]
		public System.Nullable<int> ID_Mere
		{
			get
			{
				return this._ID_Mere;
			}
			set
			{
				if ((this._ID_Mere != value))
				{
					if (this._Tiers_Tiers1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_MereChanging(value);
					this.SendPropertyChanging();
					this._ID_Mere = value;
					this.SendPropertyChanged("ID_Mere");
					this.OnID_MereChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etat", DbType="Bit")]
		public System.Nullable<bool> Etat
		{
			get
			{
				return this._Etat;
			}
			set
			{
				if ((this._Etat != value))
				{
					this.OnEtatChanging(value);
					this.SendPropertyChanging();
					this._Etat = value;
					this.SendPropertyChanged("Etat");
					this.OnEtatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsClient", DbType="Bit")]
		public System.Nullable<bool> IsClient
		{
			get
			{
				return this._IsClient;
			}
			set
			{
				if ((this._IsClient != value))
				{
					this.OnIsClientChanging(value);
					this.SendPropertyChanging();
					this._IsClient = value;
					this.SendPropertyChanged("IsClient");
					this.OnIsClientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSupplier", DbType="Bit")]
		public System.Nullable<bool> IsSupplier
		{
			get
			{
				return this._IsSupplier;
			}
			set
			{
				if ((this._IsSupplier != value))
				{
					this.OnIsSupplierChanging(value);
					this.SendPropertyChanging();
					this._IsSupplier = value;
					this.SendPropertyChanged("IsSupplier");
					this.OnIsSupplierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeClient", DbType="NVarChar(50)")]
		public string CodeClient
		{
			get
			{
				return this._CodeClient;
			}
			set
			{
				if ((this._CodeClient != value))
				{
					this.OnCodeClientChanging(value);
					this.SendPropertyChanging();
					this._CodeClient = value;
					this.SendPropertyChanged("CodeClient");
					this.OnCodeClientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeSupplier", DbType="NVarChar(50)")]
		public string CodeSupplier
		{
			get
			{
				return this._CodeSupplier;
			}
			set
			{
				if ((this._CodeSupplier != value))
				{
					this.OnCodeSupplierChanging(value);
					this.SendPropertyChanging();
					this._CodeSupplier = value;
					this.SendPropertyChanged("CodeSupplier");
					this.OnCodeSupplierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codebarre", DbType="NVarChar(50)")]
		public string Codebarre
		{
			get
			{
				return this._Codebarre;
			}
			set
			{
				if ((this._Codebarre != value))
				{
					this.OnCodebarreChanging(value);
					this.SendPropertyChanging();
					this._Codebarre = value;
					this.SendPropertyChanged("Codebarre");
					this.OnCodebarreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adresse", DbType="NVarChar(MAX)")]
		public string Adresse
		{
			get
			{
				return this._Adresse;
			}
			set
			{
				if ((this._Adresse != value))
				{
					this.OnAdresseChanging(value);
					this.SendPropertyChanging();
					this._Adresse = value;
					this.SendPropertyChanged("Adresse");
					this.OnAdresseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodePostal", DbType="NVarChar(50)")]
		public string CodePostal
		{
			get
			{
				return this._CodePostal;
			}
			set
			{
				if ((this._CodePostal != value))
				{
					this.OnCodePostalChanging(value);
					this.SendPropertyChanging();
					this._CodePostal = value;
					this.SendPropertyChanged("CodePostal");
					this.OnCodePostalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ville", DbType="NVarChar(MAX)")]
		public string Ville
		{
			get
			{
				return this._Ville;
			}
			set
			{
				if ((this._Ville != value))
				{
					this.OnVilleChanging(value);
					this.SendPropertyChanging();
					this._Ville = value;
					this.SendPropertyChanged("Ville");
					this.OnVilleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Pays", DbType="Int")]
		public System.Nullable<int> ID_Pays
		{
			get
			{
				return this._ID_Pays;
			}
			set
			{
				if ((this._ID_Pays != value))
				{
					this.OnID_PaysChanging(value);
					this.SendPropertyChanging();
					this._ID_Pays = value;
					this.SendPropertyChanged("ID_Pays");
					this.OnID_PaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Departement", DbType="Int")]
		public System.Nullable<int> ID_Departement
		{
			get
			{
				return this._ID_Departement;
			}
			set
			{
				if ((this._ID_Departement != value))
				{
					this.OnID_DepartementChanging(value);
					this.SendPropertyChanging();
					this._ID_Departement = value;
					this.SendPropertyChanged("ID_Departement");
					this.OnID_DepartementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiteWeb", DbType="NVarChar(50)")]
		public string SiteWeb
		{
			get
			{
				return this._SiteWeb;
			}
			set
			{
				if ((this._SiteWeb != value))
				{
					this.OnSiteWebChanging(value);
					this.SendPropertyChanging();
					this._SiteWeb = value;
					this.SendPropertyChanged("SiteWeb");
					this.OnSiteWebChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="NVarChar(50)")]
		public string Telephone
		{
			get
			{
				return this._Telephone;
			}
			set
			{
				if ((this._Telephone != value))
				{
					this.OnTelephoneChanging(value);
					this.SendPropertyChanging();
					this._Telephone = value;
					this.SendPropertyChanged("Telephone");
					this.OnTelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="NVarChar(50)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this.OnFaxChanging(value);
					this.SendPropertyChanging();
					this._Fax = value;
					this.SendPropertyChanged("Fax");
					this.OnFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RC", DbType="NVarChar(50)")]
		public string RC
		{
			get
			{
				return this._RC;
			}
			set
			{
				if ((this._RC != value))
				{
					this.OnRCChanging(value);
					this.SendPropertyChanging();
					this._RC = value;
					this.SendPropertyChanged("RC");
					this.OnRCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatriculeFiscal", DbType="NVarChar(50)")]
		public string MatriculeFiscal
		{
			get
			{
				return this._MatriculeFiscal;
			}
			set
			{
				if ((this._MatriculeFiscal != value))
				{
					this.OnMatriculeFiscalChanging(value);
					this.SendPropertyChanging();
					this._MatriculeFiscal = value;
					this.SendPropertyChanged("MatriculeFiscal");
					this.OnMatriculeFiscalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeDouane", DbType="NVarChar(50)")]
		public string CodeDouane
		{
			get
			{
				return this._CodeDouane;
			}
			set
			{
				if ((this._CodeDouane != value))
				{
					this.OnCodeDouaneChanging(value);
					this.SendPropertyChanging();
					this._CodeDouane = value;
					this.SendPropertyChanged("CodeDouane");
					this.OnCodeDouaneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAN", DbType="NVarChar(50)")]
		public string BAN
		{
			get
			{
				return this._BAN;
			}
			set
			{
				if ((this._BAN != value))
				{
					this.OnBANChanging(value);
					this.SendPropertyChanging();
					this._BAN = value;
					this.SendPropertyChanged("BAN");
					this.OnBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumTVA", DbType="NVarChar(50)")]
		public string NumTVA
		{
			get
			{
				return this._NumTVA;
			}
			set
			{
				if ((this._NumTVA != value))
				{
					this.OnNumTVAChanging(value);
					this.SendPropertyChanging();
					this._NumTVA = value;
					this.SendPropertyChanged("NumTVA");
					this.OnNumTVAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Assujetti", DbType="Bit")]
		public System.Nullable<bool> Assujetti
		{
			get
			{
				return this._Assujetti;
			}
			set
			{
				if ((this._Assujetti != value))
				{
					this.OnAssujettiChanging(value);
					this.SendPropertyChanging();
					this._Assujetti = value;
					this.SendPropertyChanged("Assujetti");
					this.OnAssujettiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Type", DbType="Int")]
		public System.Nullable<int> ID_Type
		{
			get
			{
				return this._ID_Type;
			}
			set
			{
				if ((this._ID_Type != value))
				{
					if (this._Tiers_Types.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_TypeChanging(value);
					this.SendPropertyChanging();
					this._ID_Type = value;
					this.SendPropertyChanged("ID_Type");
					this.OnID_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_FormeJuridique", DbType="Int")]
		public System.Nullable<int> ID_FormeJuridique
		{
			get
			{
				return this._ID_FormeJuridique;
			}
			set
			{
				if ((this._ID_FormeJuridique != value))
				{
					this.OnID_FormeJuridiqueChanging(value);
					this.SendPropertyChanging();
					this._ID_FormeJuridique = value;
					this.SendPropertyChanged("ID_FormeJuridique");
					this.OnID_FormeJuridiqueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capital", DbType="NChar(10)")]
		public string Capital
		{
			get
			{
				return this._Capital;
			}
			set
			{
				if ((this._Capital != value))
				{
					this.OnCapitalChanging(value);
					this.SendPropertyChanging();
					this._Capital = value;
					this.SendPropertyChanged("Capital");
					this.OnCapitalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Devise", DbType="NChar(10)")]
		public string ID_Devise
		{
			get
			{
				return this._ID_Devise;
			}
			set
			{
				if ((this._ID_Devise != value))
				{
					this.OnID_DeviseChanging(value);
					this.SendPropertyChanging();
					this._ID_Devise = value;
					this.SendPropertyChanged("ID_Devise");
					this.OnID_DeviseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logo", DbType="NVarChar(MAX)")]
		public string logo
		{
			get
			{
				return this._logo;
			}
			set
			{
				if ((this._logo != value))
				{
					this.OnlogoChanging(value);
					this.SendPropertyChanging();
					this._logo = value;
					this.SendPropertyChanged("logo");
					this.OnlogoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Activite", DbType="Int")]
		public System.Nullable<int> ID_Activite
		{
			get
			{
				return this._ID_Activite;
			}
			set
			{
				if ((this._ID_Activite != value))
				{
					if (this._Tiers_Activites.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ActiviteChanging(value);
					this.SendPropertyChanging();
					this._ID_Activite = value;
					this.SendPropertyChanged("ID_Activite");
					this.OnID_ActiviteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedByUserID", DbType="Int")]
		public System.Nullable<int> CreatedByUserID
		{
			get
			{
				return this._CreatedByUserID;
			}
			set
			{
				if ((this._CreatedByUserID != value))
				{
					this.OnCreatedByUserIDChanging(value);
					this.SendPropertyChanging();
					this._CreatedByUserID = value;
					this.SendPropertyChanged("CreatedByUserID");
					this.OnCreatedByUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOnDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOnDate
		{
			get
			{
				return this._CreatedOnDate;
			}
			set
			{
				if ((this._CreatedOnDate != value))
				{
					this.OnCreatedOnDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedOnDate = value;
					this.SendPropertyChanged("CreatedOnDate");
					this.OnCreatedOnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedByUserID", DbType="Int")]
		public System.Nullable<int> LastModifiedByUserID
		{
			get
			{
				return this._LastModifiedByUserID;
			}
			set
			{
				if ((this._LastModifiedByUserID != value))
				{
					this.OnLastModifiedByUserIDChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedByUserID = value;
					this.SendPropertyChanged("LastModifiedByUserID");
					this.OnLastModifiedByUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedOnDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastModifiedOnDate
		{
			get
			{
				return this._LastModifiedOnDate;
			}
			set
			{
				if ((this._LastModifiedOnDate != value))
				{
					this.OnLastModifiedOnDateChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedOnDate = value;
					this.SendPropertyChanged("LastModifiedOnDate");
					this.OnLastModifiedOnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tiers_Tiers_Tiers_Tiers", Storage="_Tiers_Tiers2", ThisKey="ID", OtherKey="ID_Mere")]
		public EntitySet<Tiers_Tiers> Tiers_Tiers2
		{
			get
			{
				return this._Tiers_Tiers2;
			}
			set
			{
				this._Tiers_Tiers2.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tiers_Activites_Tiers_Tiers", Storage="_Tiers_Activites", ThisKey="ID_Activite", OtherKey="ID", IsForeignKey=true)]
		public Tiers_Activites Tiers_Activites
		{
			get
			{
				return this._Tiers_Activites.Entity;
			}
			set
			{
				Tiers_Activites previousValue = this._Tiers_Activites.Entity;
				if (((previousValue != value) 
							|| (this._Tiers_Activites.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tiers_Activites.Entity = null;
						previousValue.Tiers_Tiers.Remove(this);
					}
					this._Tiers_Activites.Entity = value;
					if ((value != null))
					{
						value.Tiers_Tiers.Add(this);
						this._ID_Activite = value.ID;
					}
					else
					{
						this._ID_Activite = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tiers_Activites");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tiers_Tiers_Tiers_Tiers", Storage="_Tiers_Tiers1", ThisKey="ID_Mere", OtherKey="ID", IsForeignKey=true)]
		public Tiers_Tiers Tiers_Tiers1
		{
			get
			{
				return this._Tiers_Tiers1.Entity;
			}
			set
			{
				Tiers_Tiers previousValue = this._Tiers_Tiers1.Entity;
				if (((previousValue != value) 
							|| (this._Tiers_Tiers1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tiers_Tiers1.Entity = null;
						previousValue.Tiers_Tiers2.Remove(this);
					}
					this._Tiers_Tiers1.Entity = value;
					if ((value != null))
					{
						value.Tiers_Tiers2.Add(this);
						this._ID_Mere = value.ID;
					}
					else
					{
						this._ID_Mere = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tiers_Tiers1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tiers_Types_Tiers_Tiers", Storage="_Tiers_Types", ThisKey="ID_Type", OtherKey="ID", IsForeignKey=true)]
		public Tiers_Types Tiers_Types
		{
			get
			{
				return this._Tiers_Types.Entity;
			}
			set
			{
				Tiers_Types previousValue = this._Tiers_Types.Entity;
				if (((previousValue != value) 
							|| (this._Tiers_Types.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tiers_Types.Entity = null;
						previousValue.Tiers_Tiers.Remove(this);
					}
					this._Tiers_Types.Entity = value;
					if ((value != null))
					{
						value.Tiers_Tiers.Add(this);
						this._ID_Type = value.ID;
					}
					else
					{
						this._ID_Type = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tiers_Types");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tiers_Tiers2(Tiers_Tiers entity)
		{
			this.SendPropertyChanging();
			entity.Tiers_Tiers1 = this;
		}
		
		private void detach_Tiers_Tiers2(Tiers_Tiers entity)
		{
			this.SendPropertyChanging();
			entity.Tiers_Tiers1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tiers_Types")]
	public partial class Tiers_Types : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Designation;
		
		private System.Nullable<int> _CreatedByUserID;
		
		private System.Nullable<System.DateTime> _CreatedOnDate;
		
		private System.Nullable<int> _LastModifiedByUserID;
		
		private System.Nullable<System.DateTime> _LastModifiedOnDate;
		
		private EntitySet<Tiers_Tiers> _Tiers_Tiers;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDesignationChanging(string value);
    partial void OnDesignationChanged();
    partial void OnCreatedByUserIDChanging(System.Nullable<int> value);
    partial void OnCreatedByUserIDChanged();
    partial void OnCreatedOnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnDateChanged();
    partial void OnLastModifiedByUserIDChanging(System.Nullable<int> value);
    partial void OnLastModifiedByUserIDChanged();
    partial void OnLastModifiedOnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastModifiedOnDateChanged();
    #endregion
		
		public Tiers_Types()
		{
			this._Tiers_Tiers = new EntitySet<Tiers_Tiers>(new Action<Tiers_Tiers>(this.attach_Tiers_Tiers), new Action<Tiers_Tiers>(this.detach_Tiers_Tiers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Designation", DbType="NVarChar(MAX)")]
		public string Designation
		{
			get
			{
				return this._Designation;
			}
			set
			{
				if ((this._Designation != value))
				{
					this.OnDesignationChanging(value);
					this.SendPropertyChanging();
					this._Designation = value;
					this.SendPropertyChanged("Designation");
					this.OnDesignationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedByUserID", DbType="Int")]
		public System.Nullable<int> CreatedByUserID
		{
			get
			{
				return this._CreatedByUserID;
			}
			set
			{
				if ((this._CreatedByUserID != value))
				{
					this.OnCreatedByUserIDChanging(value);
					this.SendPropertyChanging();
					this._CreatedByUserID = value;
					this.SendPropertyChanged("CreatedByUserID");
					this.OnCreatedByUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOnDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOnDate
		{
			get
			{
				return this._CreatedOnDate;
			}
			set
			{
				if ((this._CreatedOnDate != value))
				{
					this.OnCreatedOnDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedOnDate = value;
					this.SendPropertyChanged("CreatedOnDate");
					this.OnCreatedOnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedByUserID", DbType="Int")]
		public System.Nullable<int> LastModifiedByUserID
		{
			get
			{
				return this._LastModifiedByUserID;
			}
			set
			{
				if ((this._LastModifiedByUserID != value))
				{
					this.OnLastModifiedByUserIDChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedByUserID = value;
					this.SendPropertyChanged("LastModifiedByUserID");
					this.OnLastModifiedByUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedOnDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastModifiedOnDate
		{
			get
			{
				return this._LastModifiedOnDate;
			}
			set
			{
				if ((this._LastModifiedOnDate != value))
				{
					this.OnLastModifiedOnDateChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedOnDate = value;
					this.SendPropertyChanged("LastModifiedOnDate");
					this.OnLastModifiedOnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tiers_Types_Tiers_Tiers", Storage="_Tiers_Tiers", ThisKey="ID", OtherKey="ID_Type")]
		public EntitySet<Tiers_Tiers> Tiers_Tiers
		{
			get
			{
				return this._Tiers_Tiers;
			}
			set
			{
				this._Tiers_Tiers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tiers_Tiers(Tiers_Tiers entity)
		{
			this.SendPropertyChanging();
			entity.Tiers_Types = this;
		}
		
		private void detach_Tiers_Tiers(Tiers_Tiers entity)
		{
			this.SendPropertyChanging();
			entity.Tiers_Types = null;
		}
	}
}
#pragma warning restore 1591
